// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwioipumxwhigrfzuytv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3aW9pcHVteHdoaWdyZnp1eXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3ODQ2NDQsImV4cCI6MjA1NTM2MDY0NH0.-t8VkKBwSZqrOvBn7Usmg_V2oq-XkTF8b6QwQFJxF30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);